### ISSUE TITLE
Problems using serval

### ISSUE THREAD

**Issue by danirevi5** [mzechmeister/serval#53]
First of all thank you for this useful tool.
I have been using it for some time but since I formatted my computer I am no longer able to run serval.
After following all the steps and try to run "serval -h" I recive different problems, with gplot, pandas, etc.
I have managed to solve some of them, but they keep appearing, for example this last one (although I have `pause` installed):
`ImportError: cannot import name 'pause' from 'pause'`
The same happens with the `wstat` module, that it says it's not installed. It looks like I am missing many packages...

When I first used `serval` in the past I didn't need to install any more packages (like that one called `pause`) or change any  code lines as I have had to do this time (in serval.py I had to change `from gplot import *` to `from ggplot import *`).
I am working on Ubuntu 20.04.4 LTS with Python 3.9.7

Thank you!

Dani

**Comment by mzechmeister** [comment]
Did you miss to install https://github.com/mzechmeister/python and to expand the path names as given in install instruction of [serval](https://github.com/mzechmeister/serval/)? That repo hosts `pause`, `gplot`, `wstat`.

```bash
git clone https://github.com/mzechmeister/python.git
export PYTHONPATH=$PYTHONPATH:$SERVALHOME/python/
```

**Comment by danirevi5** [comment]
Thank you very much.
That was just the problem and the solution.

I don't know why but although I installed it I only got installed gplot and gls.

Thank you for your help.
